# https://github.com/SeleniumHQ/docker-selenium
# To execute this docker compose yml file use `docker compose -f selenium4.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d`
# Add the `-d` flag at the end for detached execution
# http://localhost:4444/grid/console
# To stop the execution, hit Ctrl+C, and then `docker compose -f selenium4.yml down --remove-orphans`
services:
  chrome:
    image: selenium/node-chrome:4.40.0-20260202
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_CONNECTION_LIMIT_PER_SESSION=1000
      - SE_NODE_SESSION_TIMEOUT=1800

  edge:
    image: selenium/node-edge:4.40.0-20260202
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_CONNECTION_LIMIT_PER_SESSION=1000
      - SE_NODE_SESSION_TIMEOUT=1800

  firefox:
    image: selenium/node-firefox:4.40.0-20260202
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_CONNECTION_LIMIT_PER_SESSION=1000
      - SE_NODE_SESSION_TIMEOUT=1800

  selenium-hub:
    image: selenium/hub:4.40.0-20260202
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
